name: Bump Homebrew version
on:
  workflow_run:
    workflows: ["Release version"]
  types:
    - [completed]
jobs:
  on-success:
    if: ${{github.even.workflow_run.conclusion == 'success' }}
    steps:
      bump-homebrew-formula:
        runs-on: ubuntu-latest
        needs: create-release
        steps:
          - uses: mislav/bump-homebrew-formula-action@v1.12
            with:
              formula-name: dapptools-rs
            env:
              COMMITTER_TOKEN: ${{ secrets.G_TOKEN }}
