name: Bump Homebrew version
on:
  workflow_run:
    workflows: ["Release version"]
    types: [completed]
jobs:
  on-success:
    if: ${{github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1.12
        with:
          formula-name: dapptools-rs
        env:
          COMMITTER_TOKEN: ${{ secrets.G_TOKEN }}
